#include <devSymbTable.h>
SYMTAB_EXTERN(testDoubleArray)
SYMTAB_EXTERN(testDoublePtr)
SYMTAB_EXTERN(testDoubleScalar)
SYMTAB_EXTERN(testDoubleScalar)
SYMTAB_EXTERN(testLongArray)
SYMTAB_EXTERN(testLongPtr)
SYMTAB_EXTERN(testLongScalar)
SYMTAB_EXTERN(testString)
SYMTAB_EXTERN(testStringPtr)
SYMTAB_START()
SYMTAB_ENTRY(testDoubleArray)
SYMTAB_ENTRY(testDoublePtr)
SYMTAB_ENTRY(testDoubleScalar)
SYMTAB_ENTRY(testDoubleScalar)
SYMTAB_ENTRY(testLongArray)
SYMTAB_ENTRY(testLongPtr)
SYMTAB_ENTRY(testLongScalar)
SYMTAB_ENTRY(testString)
SYMTAB_ENTRY(testStringPtr)
SYMTAB_END()

